name: _打包上传制品

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - uses: yanhao98/composite-actions/setup-node-environment@main
    - run: pnpm run build
    - uses: actions/upload-artifact@v4
      with:
        name: artifact-${{ github.ref_name }}
        path: out
        retention-days: 90
